### ISSUE TITLE
Failure to precompile ViscousStreaming

### ISSUE THREAD

**Issue by quasarsrus** [jdeldre/ViscousStreaming.jl#2]
Executing 'using ViscousStreaming' results in the following error: 

┌ Info: Precompiling ViscousStreaming [103da179-b3e4-57c1-99a4-586354eb2c5a]
└ @ Base loading.jl:1278
ERROR: LoadError: LoadError: LoadError: TypeError: in PointForce, in type definition, expected Type, got a value of type typeof(CartesianGrids.PulseField)

**Comment by jdeldre** [comment]
Duplicate of JuliaIBPM/ViscousFlow.jl#56. See response there.

**Comment by quasarsrus** [comment]
Thank You!
